global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: savor
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:8000
          - identity:8001
          - catalog:8002
          - order:8003
          - payment:8004
          - courier:8005
          - notification:8006
        labels:
          project: savor
